### PR TITLE
Small Fix/Observation in Human Guidelines

### PR DESCRIPTION
**Pull request by singh96aman**

### CODE REVIEW

**Review by kartik727 — CHANGES_REQUESTED** [review]
We shouldn't change templates once we have run experiments with them. Would be better to create a new template (perhaps called `HUMAN_GUIDELINES_V1_1`) with the intended changes. Then if we need to make any further fixes in the future, we could create `HUMAN_GUIDELINES_V1_2` etc.

**Review by singh96aman — COMMENTED** [review]
Good Point!
Moved it to new HumanGuidelinesV1_2

**Review by kartik727 — COMMENTED** [review]
Can you bump the version number in `pyproject.toml` and `src/llm_eval/__init__.py` as well? Since this update just adds a new template it should be a PATCH update. `v2.1.0 -> v2.1.1`

**Review by singh96aman — COMMENTED** [review]
Updated Release No

**Review by kartik727 — APPROVED** [review]

**Pull request merged**
